add getTransactions endpoint support
stellar/rs-stellar-rpc-client pull request #3
Opened 2024-07-15 18:55 UTC by BlaineHeffron

### What

Adding support for GetTransactions endpoint

### Why

achieve feature parity with the RPC code

### Known limitations

N/A

2024-07-15 19:01 UTC, willemneal commented on src/lib.rs
> +    pub cursor: String,
Isn't this a number?

2024-07-15 19:04 UTC, willemneal commented on src/lib.rs
> +            transactions,
```suggestion
        Ok(GetTransactionsResponse {
            transactions: self.transaction.into_iter().map(TryInto::try_into).collect::<Result<Vec<_>,xdr::Error>>()?,
```
Iterators are your best friend ;-). Also probably need to do this locally to do `cargo fmt`

2024-07-15 19:05 UTC, willemneal requested changes
Looks great! Just one question and one nit

2024-07-15 19:40 UTC, BlaineHeffron commented on src/lib.rs
> +    pub cursor: String,
It is a number but it is wrapped in quotes and the Go code accepts a string. So I see no reason to convert it to a number.

2024-07-15 19:42 UTC, BlaineHeffron commented on src/lib.rs
> +            transactions,
got it, thanks!

2024-07-15 19:44 UTC, BlaineHeffron commented
Should be ready now, thanks.

2024-07-16 12:51 UTC, willemneal commented on src/lib.rs
> +    pub cursor: String,
The reason it's a number is because even though JSON it self doesn't put limits on the size of numbers JS does. So any number greater than [2^53 - 1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER). The cursor is a number and I'm sure in the go code they convert to one eventually. Not sure the size though.

2024-07-16 13:49 UTC, willemneal commented on src/lib.rs
> +    pub cursor: Option<String>,
```suggestion
   #[serde_as(as = "DisplayFromStr")]
   #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
```

2024-07-16 14:09 UTC, BlaineHeffron commented on src/lib.rs
> +    pub cursor: Option<String>,
I had to modify it a bit to get it to work but take a look

2024-07-16 14:11 UTC, willemneal commented on src/lib.rs
>      pub cursor: Option<String>,
```suggestion
    pub cursor: Option<u64>,
```

2024-07-16 16:11 UTC, BlaineHeffron commented on src/lib.rs
>      pub cursor: Option<String>,
got it, had to change the response structs as well for the seamless feeding cursor from request to response

2024-07-23 17:42 UTC, willemneal commented on src/lib.rs
> +    ValidationError(String),
Is this used anywhere?

2024-07-23 17:43 UTC, willemneal approved these changes
Just one question about the seemingly unused Error case.

2024-07-23 18:31 UTC, BlaineHeffron commented on src/lib.rs
> +    ValidationError(String),
Good catch, that was what was thrown if the validation failed but since we don't need the input validation here I removed that method. I forgot to remove the associated error.

2024-07-23 19:23 UTC, merged